name: Advanced DevSecOps Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  security-guard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: üõë Secret Scanning (Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          exit-code: "1"
          # vuln-type: "os,library"
          scanners: "secret"
          severity: "CRITICAL,HIGH"
      - name: üê≥ Build & Scan Docker Image
        if: success()
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "bkimminich/juice-shop:latest"
          format: "json"
          output: "trivy-report.json"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
      - name: üöÄ Start App Container
        if: success()
        run: |
          docker run --rm -d -p 3007:3000 --name juice-shop bkimminich/juice-shop:latest
          echo "Waiting for app to start..."
          sleep 30
      - name: ‚ö° DAST Scan (OWASP ZAP)
        if: success()
        run: |
          # C·∫•p quy·ªÅn ghi file cho th∆∞ m·ª•c hi·ªán t·∫°i
          chmod 777 $(pwd)
          # Ch·∫°y Docker ZAP, mount th∆∞ m·ª•c hi·ªán t·∫°i v√†o ƒë·ªÉ l·∫•y b√°o c√°o
          docker run --network host -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-baseline.py \
          -t http://localhost:3007 \
          -x zap-report.xml \
          -I # (T√πy ch·ªçn) -I nghƒ©a l√† b·ªè qua l·ªói c·∫£nh b√°o, n·∫øu mu·ªën pipeline ƒë·ªè khi c√≥ l·ªói th√¨ b·ªè -I ƒëi
      - name: üìÇ Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            trivy-report.json
            zap-report.xml
      - name: üîî Discord Notification
        if: always()
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "DevSecOps Bot"
          avatar-url: "https://cdn-icons-png.flaticon.com/512/2092/2092663.png"
          description: "üîí Security Scan Status: ${{ job.status }}! \nCheck GitHub Actions for details."
