name: DevSecOps Pipeline - DefectDojo Ready
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "bkimminich/juice-shop:latest"
          format: "json"
          output: "trivy-report.json"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          exit-code: "0"
      - name: Start Juice Shop Container
        run: |
          docker run --rm -d -p 3007:3000 --name juice-shop bkimminich/juice-shop:latest
          echo "Đang đợi ứng dụng khởi động..."
          sleep 30
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://localhost:3007"
          cmd_options: "-x zap-report.xml"
          allow_issue_writing: false
      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            trivy-report.json
            zap-report.xml
